spring:
#服务名称
  application:
    name: weather-hbase
#  jpa:
#    database: oracle
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#  datasource:
#      driver-class-name: oracle.jdbc.OracleDriver
#      url: jdbc:oracle:thin:@10.0.108.36:1521:weather
#      username: weather
#      password: YOUZIDATA
#HBASE配置
app:
  datasource:
    hdp:
      fs.defaultFS: hdfs://ambari01:8020
      zk-quorum: ambari03,ambari02,ambari01
      zk-port: 2181
      zookeeper.znode.parent: /hbase-unsecure
    hbase:
      master: 10.0.110.121:16000
      rootdir: hdfs://ambari01:8020/apps/hbase/data

server:
  port: 9998
  tomcat:
    uri-encoding: UTF-8
    
CSVPath: "/hadoop/sdc/test/hbasezip/"
IPADDR: "10.0.110.124"

ScheduleParam:
  #需要入库的文件目录
  FilePath: ""
  #记录已经入库的文件地址
  TxtPath: ""